datasets:
  raw:
    housing:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/housing.csv
      driver_params: {}

  processed:
    train:
      features:
        type: ds
        format: csv
        uri: ${core.data_base_path}/processed/train/features.csv
        driver_params:
          save:
            index: False
      target:
        type: ds
        format: csv
        uri: ${core.data_base_path}/processed/train/target.csv
        driver_params:
          save:
            index: False


    test:
      features:
        type: ds
        format: csv
        uri: ${core.data_base_path}/processed/test/features.csv
        driver_params:
          save:
            index: False
      target:
        type: ds
        format: csv
        uri: ${core.data_base_path}/processed/test/target.csv
        driver_params:
          save:
            index: False

  score:
      linear_reg:
        type: ds
        format: csv
        uri: ${core.data_base_path}/score/linear_reg.csv
        driver_params:
          save:
            index: False
      decision_tree:
        type: ds
        format: csv
        uri: ${core.data_base_path}/score/decision_tree.csv
        driver_params:
          save:
            index: False