jobs:
  - name: data-collection
    stages:
      - name: "download-raw-data"
        tasks:
          - name: "downloading"
            params:
              housing_url: "https://raw.githubusercontent.com/ageron/handson-ml/master/datasets/housing/housing.tgz"
              housing_path: "data/raw"

      - name: "train-test-split"
        tasks:
          - name: "creating_train_test"
            params: {}

  - name: feature-engineering-job
    stages:
      - name: "feature-engineering"
        tasks:
          - name: "perform-feature-engineering"
            params: {}

  - name: model-training-job
    stages:
      - name: "model-creation"
        tasks:
          - name: "model-training"
            params:
              param_grid:
                - n_estimators: [3, 10, 30]
                  max_features: [2, 4, 6, 8]
                - bootstrap: [False]
                  n_estimators: [3, 10]
                  max_features: [2, 3, 4]
              param_distribs:
                n_estimators:
                  randint:
                    low: 1
                    high: 200
                max_features:
                  randint:
                    low: 1
                    high: 8

  - name: model-evaluation-job
    stages:
      - name: "model-predict"
        tasks:
          - name: "model-scoring"
            params: {}
